### ISSUE TITLE
Dataset help

### ISSUE THREAD

**Issue by cheny124800** [MarioProjects/MnMsCardiac#1]

**Comment by cheny124800** [comment]
In the fold of the original M&Ms dataset, there is no M&Ms Dataset Information.xlsx file, can you provide the dataset you have processed.  Thanks a lot.

**Comment by MarioProjects** [comment]
Hi @cheny124800, the competition dataset is slightly different from the final released dataset due to some patient permission rights. I can't provide you with the competition dataset, sorry.

**Comment by cheny124800** [comment]
Thanks for your reply, so how can I train the model based on the competition dataset (final released dataset ), how to use your code on it, please help me, thanks a lot！

**Comment by MarioProjects** [comment]
Sorry @cheny124800 but I can't provide you the complete code for the latest release. You can reuse this repo and change the dataloader (https://github.com/MarioProjects/MnMsCardiac/blob/master/utils/dataload.py) to your needs.

**Comment by cheny124800** [comment]
Thanks a lot, I do not want complete code for the latest release, can you provide the code work on the competition dataset (not the final released dataset, just download from the website, the original dataset), I am not familiar with this dataset, it is hard for me to change the dataloader to work on this dataset, thanks for your help!

**Comment by cheny124800** [comment]
Thanks a lot, I do not want complete code for the latest release, can you provide the code work on the final released dataset (not the competition dataset), I am not familiar with this dataset, it is hard for me to change the dataloader to work on this dataset, thanks for your help!

**Comment by cheny124800** [comment]
Can you give a detailed illustration about how to change the dataloader.py to adapt to the final released dataset, thanks a lot!  Hope for your reply!
